### PR TITLE
ci: add a updated ci with linter check

### LINKED ISSUE #8: [Feature Request]: Add Go a Linter in CI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a Go linter to  analyzes incoming source code for errors, bugs, and other issues

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
### Issue

Closes #8 

### Chnages
- Add a Go Linter check for incoming PR to analyse source code for errors, bugs, and other issues.

### CODE REVIEW

**Comment by vigneshs-dev** [comment]
image

I am experiencing the above errors for pull request from contributors. Can you solve this error along with the linter part?

**Comment by Pradumnasaraf** [comment]
I will fix that. I see you delete the workflows folder

**Comment by Pradumnasaraf** [comment]
Hey, @vigneshs-dev

 I have fixed the issue. Approve the workflow run in the PR and test.

**Comment by Pradumnasaraf** [comment]
Hey, @vigneshs-dev

 I have fixed the issue. Approve the workflow run in the PR and test.

**Comment by Pradumnasaraf** [comment]
Hey, @vigneshs-dev

 I have fixed the issue. Approve the workflow run in the PR and test.

**Review by vigneshs-dev — APPROVED** [review]

**Comment by vigneshs-dev** [comment]
Thankyou for your contribution. Keep contributing.

**Comment by Pradumnasaraf** [comment]
Hey, 

You merged the PR even though the CI was falling. The  `golangci/golangci-lint-action@v6` was falling and everything was working fine because you changed the project structure and it's not able to locate the go file.

**Pull request merged**
