### PR TITLE
ci: fix breaking Golang Linter

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
Fix the breaking Golang Linter.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
It's working now. Giving the issues in the Code.

Screenshot 2024-10-24 at 11 21 31 PM

You can merge it and fix those issues later by raising a PR!

**Comment by Pradumnasaraf** [comment]
Hey,

Can you please merge this? And check the comment in #10?

**Comment by Pradumnasaraf** [comment]
Hey @vigneshs-dev,

Will you merge this PR?

**Comment by vigneshs-dev** [comment]
> Hey @vigneshs-dev,
> 
> Will you merge this PR?

Sorry for late reply. I will merge it with main branch. Thankyou for your contribution. @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
Thanks

**Pull request merged**
