### PR TITLE
Dockerized the project 

### PR DESCRIPTION
**Pull request by relaxgameing**
issue:[Feature Request]: Dockerize Golang-To-Do-App #1

dockerized the project , 

## changes made 
created a docker compose to easily manage the project 
changed the project file structure -> moved the backend to it's own server folder

### CODE REVIEW

**Comment by vigneshs-dev** [comment]
Hi @relaxgameing , I tried to run the docker-compose file. But, I got the error. Have you checked this in your local system. There are three lines in main.go file related to cors, which are commented. If you uncomment that and run, the project will run in your local system. You have to give MongoDB URI. 

image

Please check that.

**Comment by relaxgameing** [comment]
Yes I have checked , it run as expected.

What I think happen with you is that you ran it with ENV=production and you code looks for env file then which is not there so try by making a .env file in server 

And as per the cors problem that I didn't touch because I didn't wanted to change code and tried to kept it as original as possible, so patch and delete methods are blocked , apply the cors should solve the problem, I will change these and get back to you later. 

Thank you for replying

**Comment by vigneshs-dev** [comment]
I will check today and confirm the same.

**Comment by relaxgameing** [comment]
i have done the required changes and tested them in my local env now you can make all the requests and removed the requirement for .env file during development mode ,
please check and let me know if there is still some revision required

**Comment by relaxgameing** [comment]
You addressed three problems:
1.cors
2.development
3.server folder

So for cors we can just use an conditional to add cors only in development 

And for the environment variables I think having one place for all the env variables is better , we can just add or remove the variables in the compose file ( which would work for both production and development as for development we need our own values and for production you can adjust it while deploying) ( correct me if I am wrong) 

And regarding the server folder i think seperating the backend and frontend makes sense rather than having backend code in the parent folder of client ( originally)

If you accept these solution then I would change the code and I will look into deploying them in railway app and let you know about the results 

Thank you for replying

**Comment by relaxgameing** [comment]
@vigneshs-dev  hey i have deployed my updated code in railway and it deployed nicely here is the link https://golang-to-do-app-production-ff7f.up.railway.app/

**Comment by vigneshs-dev** [comment]
> @vigneshs-dev hey i have deployed my updated code in railway and it deployed nicely here is the link https://golang-to-do-app-production-ff7f.up.railway.app/

Nice @relaxgameing . Then there will be no problem in merging also. I will merge your code with the main branch. Thank you for your great work and contribution. You have given full effort on this issue. Sooperub dedication. Keep contributing.

**Pull request merged**
